### ISSUE TITLE
Javascript error when disabling dropdown fields

### ISSUE THREAD

**Issue by JasonRuthkoski** [DavidLozzi/SharePoint-HideDisableFields#1]
Hi David,

We're using your script on a small project here in Chicago and it's come in very handy!  I did want to let you know about one issue we found though, it doesn't work for disabling dropdown fields.  The javascript error was "undefined variable not allowed in strict mode" or something to that effect.

The error occurs on line 75, and appears to be due to the "theControls" variable not being defined.  We added a "var" declaration and it fixed it.  Just wanted to let you know!

Jason Ruthkoski
![jserror](https://user-images.githubusercontent.com/12210821/37789421-d656cb46-2dd1-11e8-916c-1ebbb17f294c.JPG)

**Comment by DavidLozzi** [comment]
Awesome, thanks, I'll update the code!
