### ISSUE TITLE
Disable field manage metadata

### ISSUE THREAD

**Issue by JoselitoSouza** [DavidLozzi/SharePoint-HideDisableFields#2]
Morning David,

how disable a field manage metadata?

**Comment by DavidLozzi** [comment]
Should work the same way as other fields, are you experiencing an issue?

**Comment by JoselitoSouza** [comment]
This is my field:
![image](https://user-images.githubusercontent.com/12137265/53112516-28b8c700-351e-11e9-8183-62fd8c275d8f.png)

**Comment by JoselitoSouza** [comment]
<div class="ms-taxonomy-fieldeditor ms-taxonomy-fieldeditor-standard ms-taxonomy-writing" title="TesteSharePointMetaDados" style="width: 364px;"><div id="TesteSharePointMetaDados_$containereditableRegion" contenteditable="true" role="textbox" aria-autocomplete="both" aria-haspopup="true" aria-multiline="true" class="ms-rtestate-write ms-taxonomy-writeableregion ms-inputBox ms-inputBoxActive" disableribboncommands="True" allowmultilines="false" restrictpastetotext="True" rtedirty="true">&#8203;</div></div>

**Comment by DavidLozzi** [comment]
Not sure... can you post a screenshot of the field configuration (Edit the field) and what it looks like BEFORE running this code? This'll help me level set what's going on.

**Comment by JoselitoSouza** [comment]
![configuration field](https://user-images.githubusercontent.com/12137265/53170442-df6c8400-35be-11e9-85ad-d02dd9ccbda1.jpg)
![html](https://user-images.githubusercontent.com/12137265/53170443-df6c8400-35be-11e9-83a1-9572a0ae502f.jpg)

**Comment by DavidLozzi** [comment]
That all looks good. What's happening exactly? Is it erroring? Have you tried using it like `Lozzi.Fields.disable("TestSharePointMEtaDados")`?
