### ISSUE TITLE
Boolean Filed

### ISSUE THREAD

**Issue by farhanfaiz** [DavidLozzi/SharePoint-HideDisableFields#3]
First, great work and thanks a lot for sharing with community.

Boolean field is not working fine. In Edit form, if I check yes, it is not rendering as yes.

![image](https://user-images.githubusercontent.com/7880346/54876284-4b156b80-4e61-11e9-9d1c-54db8037bfc6.png)

![image](https://user-images.githubusercontent.com/7880346/54876285-5a94b480-4e61-11e9-981c-351cdbd508f4.png)

**Comment by DavidLozzi** [comment]
Sorry for not responding sooner!! I just saw this. I’ll take a look and let you know

**Comment by DavidLozzi** [comment]
Try the latest version and let me know!
